deprecation note added to the chef backend docs
chef/chef-server pull request #2515
Opened 2021-05-31 08:38 UTC by dishanktiwari2501

Signed-off-by: Dishank Tiwari <dtiwari@progress.com>

### Description

The origin of this PR : https://github.com/chef/chef-web-docs/issues/3063

The deprecation note has been added to the Chef Backend docs. The warning has already been added and merged to the chef-web-docs repo via https://github.com/chef/chef-web-docs/pull/3120 PR.

2021-06-01 12:28 UTC, PrajaktaPurohit approved these changes

2021-06-01 19:24 UTC, kagarmoe commented
You appear to have a warning inside of a warning.
![Screen Shot 2021-06-01 at 12 23 11 PM](https://user-images.githubusercontent.com/4400151/120379182-3ac86900-c2d4-11eb-87e0-30ba01fe57cf.png)

Try reducing it to just the shortcode.

2021-06-01 19:26 UTC, kagarmoe requested changes
Simplifying to:

```
{{% EOL_backend %}}
```
should work

2021-06-02 18:14 UTC, kagarmoe approved these changes
![tenor-192021725](https://user-images.githubusercontent.com/4400151/120531613-af161180-c393-11eb-8ad4-fa241e498322.gif)

2021-06-02 20:18 UTC, merged