Replaced /main/ from /master/
chef/chef-server pull request #2828
Opened 2021-09-27 11:50 UTC by dishanktiwari2501

Signed-off-by: Dishank Tiwari <dtiwari@progress.com>

### Description

Update /master/ to /main/ across the documentation.

### Check List

- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-09-27 12:54 UTC, PrajaktaPurohit approved these changes

2021-09-27 19:27 UTC, kagarmoe requested changes
Two changes to confirm

2021-09-27 19:27 UTC, kagarmoe commented on docs-chef-io/content/server/config_rb_backend.md
> +  <https://github.com/cmullaparthi/ibrowse/blob/main/doc/ibrowse.html>).
please confirm

2021-09-27 19:27 UTC, kagarmoe commented on docs-chef-io/content/server/config_rb_backend.md
> +See <https://github.com/seth/pooler/blob/main/README.org> for details.
please confirm

2021-09-29 17:26 UTC, kagarmoe approved these changes
![tenor-21141053](https://user-images.githubusercontent.com/4400151/135318748-58112002-94f1-4636-95e0-12e633b0f967.gif)

2021-09-29 17:36 UTC, merged