Adding docs for policy APIs and chef-zero
chef/chef-server pull request #2898
Opened 2021-10-21 11:28 UTC by vinay-satish

### Description

Updating the documentation of policy APIs and chef-zero

### Check List

- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

2021-11-04 18:39 UTC, IanMadd commented on docs-chef-io/content/server/api_chef_server.md
> +The `POST` method is used to add a key for the specified client. This method has no parameters.
We should keep all the text saying "This method has no parameters." on a separate line.

2022-02-16 00:28 UTC, tas50 commented on dev-docs/HOW_THINGS_WORK.md
> +{{< note >}}
This isn't a page that gets rendered so this note syntax won't work

2022-02-24 14:52 UTC, PrajaktaPurohit approved these changes

2022-02-25 01:44 UTC, kagarmoe requested changes

2022-02-25 01:44 UTC, kagarmoe commented on dev-docs/HOW_THINGS_WORK.md
> +{{< note >}}
```suggestion
```

2022-02-25 01:44 UTC, kagarmoe commented on dev-docs/HOW_THINGS_WORK.md
> +{{< /note >}}
```suggestion
```

2022-02-25 01:44 UTC, kagarmoe commented on dev-docs/HOW_THINGS_WORK.md
> +
```suggestion
Note:
```

2022-02-25 01:44 UTC, kagarmoe commented on docs-chef-io/content/server/api_chef_server.md
> +The `POST` method is used to add a key for the specified client. This method has no parameters.
```suggestion
The `POST` method is used to add a key for the specified client. 

This method has no parameters.
```

2022-02-25 01:48 UTC, kagarmoe approved these changes

2022-02-25 01:49 UTC, merged