Updating habitat build channel to stable2021q2
chef/chef-server pull request #2961
Opened 2021-11-23 11:41 UTC by vinay-satish

Signed-off-by: Vinay Satish <vinay.satish@progress.com>

### Description

Currently when we do the chef-server release, the chef-server components for the habitat environment are built on the `stable` channel, meaning the dependencies are pulled from `stable` channel. The chef-server components are use in the automate environment. When we try to update the version of chef-server components in the automate we are getting dependency check failure as all the dependencies in the automate environment are pulled from the `stable2021q2` channel. We need to build the chef-server components in the `stable2021q2` in order for it to be comparable with the automate.

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

2021-11-25 05:24 UTC, jashaik commented on src/oc_bifrost/schema/sqitch.plan
> +%uri=https://github.com/chef/oc_bifrost
This URI(https://github.com/chef/oc_bifrost) is looking like working with automate. Could you please update in all the sqitch.plan files. These changes can resolve https://github.com/chef/chef-server/issues/2803 issue

2021-11-25 05:25 UTC, jashaik requested changes

2021-11-25 05:25 UTC, jashaik commented on src/oc_erchef/schema/sqitch.plan
> +%uri=https://github.com/chef/enterprise-chef-server-schema
This URI(https://github.com/chef/oc_bifrost) is looking like working with automate. Could you please update in all the sqitch.plan files. These changes can resolve #2803 issue

2021-11-25 05:27 UTC, jashaik commented
@PrajaktaPurohit This PR can also resolve #2803  issue

2021-12-17 17:19 UTC, PrajaktaPurohit approved these changes

2021-12-20 15:01 UTC, PrajaktaPurohit approved these changes

2021-12-21 06:57 UTC, vinay-satish commented
Adhoc build - https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds?branch=zei%2Fupdating_habitat_package_build

2021-12-21 06:57 UTC, merged