Adding preflight validation for search engine
chef/chef-server pull request #3181
Opened 2022-02-16 13:55 UTC by vinay-satish

Signed-off-by: Vinay Satish <vinay.satish@progress.com>

### Description

The search will not work as required if the indexes are configured to read-only. This PR adds a preflight validation to make sure that indexes are not read-only

### Issues Resolved
https://github.com/chef/chef-server/issues/3109

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

2022-02-22 09:43 UTC, vinay-satish commented
Adhoc build - https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3938

2022-02-24 15:32 UTC, jashaik commented
Pipielines -
Adhoc - https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3967

2022-02-24 20:05 UTC, tas50 commented on omnibus/files/server-ctl-cookbooks/infra-server/libraries/preflight_indexing_validator.rb
> +      The elasticsearch index configuration is set to read only.
```suggestion
      The Elasticsearch index configuration is set to read only.
```

2022-02-24 20:06 UTC, tas50 commented on omnibus/files/server-ctl-cookbooks/infra-server/libraries/preflight_indexing_validator.rb
> +      INDEX007: Invalid elasticsearch configuration
```suggestion
      INDEX007: Invalid Elasticsearch configuration
```

2022-02-25 17:44 UTC, tas50 commented
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3980

2022-02-28 09:28 UTC, jashaik commented
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3986

2022-02-28 11:00 UTC, jashaik commented
https://buildkite.com/chef/chef-umbrella-main-chef-server/builds/1090

2022-02-28 19:50 UTC, marcparadise approved these changes

2022-02-28 21:26 UTC, marcparadise commented on omnibus/files/server-ctl-cookbooks/infra-server/libraries/preflight_indexing_validator.rb
> +        if response['chef']['settings']['index'].key?('blocks')
These can be combined with `response.dig('chef', 'settings', 'index', 'blocks', 'read_only_allow_delete)`

2022-03-01 14:07 UTC, lbakerchef requested changes

2022-03-02 06:14 UTC, jashaik commented on omnibus/files/server-ctl-cookbooks/infra-server/libraries/preflight_indexing_validator.rb
> +        Chef::Log.debug('Elasticsearch is not yet up so skipping search engine permissions check.')
I will look into it. Thanks for finding it.

2022-03-02 13:36 UTC, PrajaktaPurohit approved these changes

2022-03-03 23:54 UTC, lbakerchef commented on omnibus/files/server-ctl-cookbooks/infra-server/libraries/preflight_indexing_validator.rb
> +        Chef::Log.debug('Elasticsearch is not yet up so skipping search engine permissions check.')
I saw your screenshot triggering the error - thanks.  I ran an umbrella to confirm it does not trigger under normal circumstances.

https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/4010
https://buildkite.com/chef/chef-umbrella-main-chef-server/builds/1098

2022-03-03 23:55 UTC, lbakerchef approved these changes

2022-03-04 06:26 UTC, merged