[CHEF-6088 CHEF-6094 CHEF-6107] Cookie policy, Privacy policy, logo and favicon changes
chef/chef-server pull request #3737
Opened 2023-11-15 08:28 UTC by ayush-billore

### Description

- Adds cookie policy
- Update logo
- Update  favicon

https://chefio.atlassian.net/browse/CHEF-6088
https://chefio.atlassian.net/browse/CHEF-6094
https://chefio.atlassian.net/browse/CHEF-6107

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

2023-11-22 13:05 UTC, RoyShravani commented
LGTM!

2023-11-22 15:43 UTC, RoyShravani approved these changes

2023-12-04 06:29 UTC, RajeshPaul38 commented on src/oc-id/lib/assets/images/progress-chef-logo.png
This file is not being used. We can skip it in that case.

2023-12-06 08:28 UTC, ayush-billore commented on src/oc-id/lib/assets/images/progress-chef-logo.png
@RajeshPaul38  I added both png and svg as earlier also there were both versions.

2023-12-07 12:23 UTC, saghoshprogress approved these changes

2023-12-13 22:49 UTC, marcparadise approved these changes

2023-12-13 22:50 UTC, marcparadise commented
This looks good, but probably needds a rebase on main to get  verify tests passing.

2023-12-13 23:02 UTC, marcparadise requested changes
This looks fine, but needs a rebase to getverification passing. 

Please also update the commit message to include a summary of the change and the reason the change is being implemented. ..

2023-12-14 05:57 UTC, ayush-billore commented
> This looks fine, but needs a rebase to getverification passing.
> 
> Please also update the commit message to include a summary of the change and the reason the change is being implemented. ..

Thanks for the suggestion @marcparadise 

I have added following comment -

```
The PR adds following GDPR complaiance related changes to OCID component
- add cookie policy to the footer
- update logos to reflect current Progress Chef brand.
- update favicon to reflect current Progress Chef brand.

Signed-off-by: ayush-billore <ayush.billore@progress.com>
```

2023-12-14 14:05 UTC, jashaik approved these changes

2023-12-14 14:05 UTC, merged