Knife issue: when Opensearch has limitation of page size.
chef/chef-server pull request #3951
Opened 2024-12-02 13:04 UTC by talktovikas

### Description

[Please describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

2024-12-02 18:56 UTC, marcparadise requested changes
The changes look fine. Once tests are passing could you squash commits and include a descriptive commit message - it should reference the ticket, as well as a 'why' explanation for the change itself.

2024-12-09 08:03 UTC, jashaik commented on omnibus/files/server-ctl-cookbooks/infra-server/templates/default/oc_erchef.config.erb
> +            {track_total_hits,true},
read the config value from default.rb from attributes(Omnibus).

2024-12-09 08:03 UTC, jashaik commented on omnibus/files/server-ctl-cookbooks/infra-server/templates/default/oc_erchef.config.erb
> +            {track_total_hits,true},
Default value should be false for `track_total_hits`

2024-12-09 08:04 UTC, jashaik commented on src/oc_erchef/apps/chef_index/src/chef_index_query.erl
> +                     track_total_hits = envy:get(chef_index, track_total_hits, true, boolean),
```suggestion
                     track_total_hits = envy:get(chef_index, track_total_hits, false, boolean),
```

2024-12-12 12:39 UTC, talktovikas commented
Verify Pipline: https://buildkite.com/chef/chef-chef-server-main-verify/builds/11245
Adhoc: https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/6918

2024-12-15 13:44 UTC, talktovikas commented
Umbrella: https://buildkite.com/chef/chef-umbrella-main-chef-server/builds/2582#_

2024-12-16 04:49 UTC, talktovikas commented
Video Demo for this: [knife_search_issue.mov](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EWA5Pw61aj5GvfhjpxQe0SoB276E7Z24VWgRP7uNsNTjdA?e=PxjUHC&xsdata=MDV8MDJ8fGUzNzJkNWE2ODY3ODRlMmNmZmMzMDhkZDFiNzM4YTI5fGRiMjY2YTY3Y2JlMDRkMjZhZTFhZDA1ODFmZTAzNTM1fDB8MHw2Mzg2OTY5MDUyMDk2NzU3MTV8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPak0xTWpaalptWTBMVEV4TURFdE5HVXpOQzA1WlRObUxXRTFZVEkyWm1ZelpqRTRNMTlpWmpNMVpESTRZeTB4WWprMkxUUTVNR010T0dZNE9TMDBZalppWTJFek1EWTBORGhBZFc1eExtZGliQzV6Y0dGalpYTXZiV1Z6YzJGblpYTXZNVGN6TkRBNU16Y3hPVFE1TlE9PXw2ZDFiOTAwNmRjYjM0OTYxZmZjMzA4ZGQxYjczOGEyOXwzOWJiM2I0NTg4ZDM0MGZjYTllY2NlNzc0MzgwNmQ5OQ%3D%3D&sdata=VXF0bGRxbWpHMGdTQTBGTXh4cDlkVWZpVzZsNjJWS3N5ditQazB3WW5lND0%3D&ovuser=db266a67-cbe0-4d26-ae1a-d0581fe03535%2Cvikasya%40progress.com)

2024-12-18 15:35 UTC, marcparadise approved these changes

2024-12-23 10:45 UTC, talktovikas commented
PR for AUTOMATE:https://github.com/chef/automate/pull/8699
Demo Video: https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/ER7ArTDUvsVNmUHhZ7siOGQB2XCFTRwfRgV5Ft-M22SFFA?e=lCfbmk

2024-12-23 16:27 UTC, talktovikas commented
Verify: https://buildkite.com/chef/chef-chef-server-main-verify/builds/11295#_

2024-12-24 04:53 UTC, jashaik approved these changes

2024-12-24 04:55 UTC, merged